### ISSUE TITLE
[Backend] model issue about PreferenceTag

### ISSUE THREAD

**Issue by syhsyh9696** [matatabinoneko/2021-rakuten-hackathon-team3#29]
There is an issue on PreferenceTag.

`
class PreferenceTag(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, blank=False)
    def __str__(self):
        return self.get_name_display()
`
but fix like this.

**Comment by Katsumi-N** [comment]
I fixed this issue on `fix/`preferencetagserializer` branch

then, for example, user API's output is below
`[
    {
        "loginid": "tanaka1",
        "username": "tanaka1",
        "firstname": "ichiro",
        "lastname": "tanaka",
        "iconimage": null,
        "birthday": "1995-01-01",
        "zipcode": "158-0094",
        "address": "Futakotamagawa, Setagaya-ku, Tokyo",
        "is_recommend": false,
        "friends": [
            {
                "loginid": "tanaka2",
                "username": "tanaka2",
                "birthday": "1995-01-01"
            },
            {
                "loginid": "watanabe1",
                "username": "watanabe1",
                "birthday": "1996-01-01"
            }
        ],
        "tags": [
            {
                "id": 2,
                "name": "メンズファッション"
            }
        ]
    },`

**Comment by Katsumi-N** [comment]
solved
